"""user

Revision ID: c30f504933cc
Revises: 037ac5abb3b9
Create Date: 2020-11-18 19:44:39.845869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30f504933cc'
down_revision = '037ac5abb3b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('neck', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('waist', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'waist')
    op.drop_column('user', 'neck')
    # ### end Alembic commands ###
