"""training

Revision ID: ffdfe694adfd
Revises: c81ae78ea1bd
Create Date: 2020-11-03 18:59:56.503126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffdfe694adfd'
down_revision = 'c81ae78ea1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('exNum', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training', 'exNum')
    # ### end Alembic commands ###
